<?php
return [
    'file'=>[
        'type'=>'file',
        'debug'=>true,
        'pconnect'=>0,
        'autoconnect'=>0,
    ],
    'memcache'=>[
        'hostname'=>'localhost',
        'port'=>11211,
        'type'=>'memcache',
        'debug'=>true,
        'pconnect'=>0,
        'autoconnect'=>0,
        'pre'=>'@ns_ls_',
        'ismaster'=>true,
    ],
    'redis'=>[
        'hostname'=>'127.0.0.1',
        'port'=>6379,
        'timeout'=>0,
        'type'=>'redis',
        'debug'=>true,
        'pconnect'=>0,
        'autoconnect'=>0,
        'pre'=>'@ns_ls_',
        'isusecluster'=>false,
    ],
        'apc'=>[
        'type'=>'apc',
        'pre'=>'@ns_ls_',
    ],
        'xcache'=>[
        'type'=>'xcache',
        'pre'=>'@ns_ls_',
    ],
    'eaccelerator'=>[
        'type'=>'eaccelerator',
        'pre'=>'@ns_ls_',
    ],
    '__pre'=>'TnPGcc_',
];